### PR TITLE
TCP Server: Expose a config directive to select the interface to bind.

### PR DESCRIPTION
**Pull request by dbalan**
Some setups should be fine with listening on a local port and a local aggregator pushing logs to the deamon, its better not start an insecure tcp server on a public port be default.

### CODE REVIEW

**Comment by portertech** [comment]
@dbalan I'd like it to be `0.0.0.0` by default, as in most cases it makes sense, and it makes this change backwards compatible.

**Comment by dbalan** [comment]
here you go!

**Comment by dbalan** [comment]
@portertech bump?

**Comment by portertech** [comment]
Awesome, thanks! Will merge when I'm back at my machine.

**Comment by portertech** [comment]
@dbalan new jar is up :+1:

**Comment by dbalan** [comment]
Cool. Thanks

**Pull request merged**
